language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t jsc89/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jsc89/react-test npm test

after_success:
  - docker build -t jsc89/multi-client ./client
  - docker build -t jsc89/multi-server ./server
  - docker build -t jsc89/multi-nginx ./nginx
  - docker build -t jsc89/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jsc89/multi-client
  - docker push jsc89/multi-nginx
  - docker push jsc89/multi-server
  - docker push jsc89/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-024347359975'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

notifications:
  email:
    recipients:
      - janek.stoeck@akra.de
    on_success: always # default: change
    on_failure: always # default: always