language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t jsc89/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jsc89/react-test npm test

after_success:
  - docker build -t jsc89/multi-client -f ./client
  - docker build -t jsc89/multi-server -f ./server
  - docker build -t jsc89/multi-nginx -f ./nginx
  - docker build -t jsc89/multi-worker -f ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jsc89/multi-client
  - docker push jsc89/multi-nginx
  - docker push jsc89/multi-server
  - docker push jsc89/multi-worker

notifications:
  email:
    recipients:
      - janek.stoeck@akra.de
    on_success: always # default: change
    on_failure: always # default: always